name: MCDemineur
author: GartoxFR
version: 0.1
description: le bon vieux démineur sur Minecraft
main: fr.gartox.mcdemineur.Main
commands:
  mcdemineur:
    usage: /mcd
    description: Ouvre le démineur
    aliases:
      -mcd
  dspectate:
    usage: /dspectate <joueur>
    description: Regardez la partie de quelqu'un